language: node_js
node_js:
  - "node"
  - "6"
addons:
  firefox: "latest-esr"
script: npm test
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
